/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as RencanakanKunjunganRouteImport } from './routes/rencanakan-kunjungan'
import { Route as DesaIndexRouteImport } from './routes/desa.index'
import { Route as DesaSlugRouteImport } from './routes/desa.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const RencanakanKunjunganRoute = RencanakanKunjunganRouteImport.update({
  id: '/rencanakan-kunjungan',
  path: '/rencanakan-kunjungan',
  getParentRoute: () => rootRouteImport,
} as any)
const DesaIndexRoute = DesaIndexRouteImport.update({
  id: '/desa/',
  path: '/desa/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesaSlugRoute = DesaSlugRouteImport.update({
  id: '/desa/$slug',
  path: '/desa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/galeri': typeof GaleriRoute
  '/rencanakan-kunjungan': typeof RencanakanKunjunganRoute
  '/desa/$slug': typeof DesaSlugRoute
  '/desa/': typeof DesaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/galeri': typeof GaleriRoute
  '/rencanakan-kunjungan': typeof RencanakanKunjunganRoute
  '/desa/$slug': typeof DesaSlugRoute
  '/desa': typeof DesaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/galeri': typeof GaleriRoute
  '/rencanakan-kunjungan': typeof RencanakanKunjunganRoute
  '/desa/$slug': typeof DesaSlugRoute
  '/desa/': typeof DesaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/galeri'
    | '/rencanakan-kunjungan'
    | '/desa/$slug'
    | '/desa/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/galeri'
    | '/rencanakan-kunjungan'
    | '/desa/$slug'
    | '/desa'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/galeri'
    | '/rencanakan-kunjungan'
    | '/desa/$slug'
    | '/desa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  GaleriRoute: typeof GaleriRoute
  RencanakanKunjunganRoute: typeof RencanakanKunjunganRoute
  DesaSlugRoute: typeof DesaSlugRoute
  DesaIndexRoute: typeof DesaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rencanakan-kunjungan': {
      id: '/rencanakan-kunjungan'
      path: '/rencanakan-kunjungan'
      fullPath: '/rencanakan-kunjungan'
      preLoaderRoute: typeof RencanakanKunjunganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desa/': {
      id: '/desa/'
      path: '/desa'
      fullPath: '/desa/'
      preLoaderRoute: typeof DesaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desa/$slug': {
      id: '/desa/$slug'
      path: '/desa/$slug'
      fullPath: '/desa/$slug'
      preLoaderRoute: typeof DesaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  GaleriRoute: GaleriRoute,
  RencanakanKunjunganRoute: RencanakanKunjunganRoute,
  DesaSlugRoute: DesaSlugRoute,
  DesaIndexRoute: DesaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
